# Numpy <hr style="border:3.5px solid rgba(41, 225, 106, 0.76)"></hr>

<b>Cyrus James F. Lozada</b>
<br>Computer Engineering 2-A

In [1]:
import numpy as np
from scipy import stats
from statistics import multimode

# 1D Array

In [2]:
may_array = np.array([1, 2, 3])
may_array

array([1, 2, 3])

In [3]:
type(may_array)

numpy.ndarray

In [4]:
np.shape(may_array)

(3,)

In [5]:
june_array = np.array([4, 5, 6])
june_array


array([4, 5, 6])

# 2d Array

In [6]:
july_array = np.array([[1, 2, 3], 
                      [4, 5, 6]])
july_array

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.shape(july_array)

(2, 3)

In [8]:
t_array = july_array.T
t_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [9]:
np.shape(t_array)

(3, 2)

# Measure of Central Tendency

In [10]:

resistance = np.array([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 3, 10.4, 9.8],
    [10.1, 11, 9.1, 9.2, 10.8, 20, 9.9, 9.2, 9.1, 9.1,np.nan]
    ])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. ,  3. , 10.4,  9.8],
       [10.1, 11. ,  9.1,  9.2, 10.8, 20. ,  9.9,  9.2,  9.1,  9.1,  nan]])

In [11]:
np.shape(resistance)

(2, 11)

In [12]:
resistance.T

array([[10.6, 10.1],
       [ 9.1, 11. ],
       [ 9.3,  9.1],
       [ 9.8,  9.2],
       [10.5, 10.8],
       [10.4, 20. ],
       [ 9.5,  9.9],
       [11. ,  9.2],
       [ 3. ,  9.1],
       [10.4,  9.1],
       [ 9.8,  nan]])

In [13]:
np.mean(resistance, axis=0)

array([10.35, 10.05,  9.2 ,  9.5 , 10.65, 15.2 ,  9.7 , 10.1 ,  6.05,
        9.75,   nan])

In [14]:
np.mean(resistance, axis=1)

array([9.4, nan])

In [15]:
np.nanmean(resistance, axis=1)

array([ 9.4 , 10.75])

In [16]:
jag_mean = np.nanmean(resistance, axis=1)[0]
pan_mean = np.nanmean(resistance, axis=1)[1]

print(f'jaguar_mean = {jag_mean:.2f} ohms')
print(f'panther_mean = {pan_mean:.2f} ohms')

jaguar_mean = 9.40 ohms
panther_mean = 10.75 ohms


In [17]:
np.nanmedian(resistance, axis=1)

array([9.8 , 9.55])

In [18]:
jag_median = np.nanmedian(resistance, axis=1)[0]
pan_median = np.nanmedian(resistance, axis=1)[1]

print(f'jaguar_median = {jag_median:.2f} ohms')
print(f'panther_median = {pan_median:.2f} ohms')

jaguar_median = 9.80 ohms
panther_median = 9.55 ohms


In [19]:
stats.mode(resistance, axis=1)

ModeResult(mode=array([9.8, 9.1]), count=array([2, 3]))

In [20]:
this_array = [1, 1, 2, 2, 3, 4, 5]
multimode(this_array)

[1, 2]

In [21]:
jag_res = resistance[0]

print("Jaguar mode:")
for i in multimode(jag_res):
    print(f'{i} ohms')

Jaguar mode:
9.8 ohms
10.4 ohms


In [22]:
pan_res = resistance[1]

print("Panther mode:")
for i in multimode(pan_res):
    print(f'{i} ohms')

Panther mode:
9.1 ohms


# Measures of Variability


In [23]:
resistance = np.array([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 3, 10.4, 9.8],
    [10.1, 11, 9.1, 9.2, 10.8, 20, 9.9, 9.2, 9.1, 9.1,np.nan]
    ])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. ,  3. , 10.4,  9.8],
       [10.1, 11. ,  9.1,  9.2, 10.8, 20. ,  9.9,  9.2,  9.1,  9.1,  nan]])

In [24]:
res_max = np.nanmax(resistance, axis=1)
res_min = np.nanmin(resistance, axis=1)

res_range = res_max - res_min
res_range

array([ 8. , 10.9])

In [25]:
print(f'Jaguar resistance range: {res_range[0]:.2f} ohms')
print(f'Panther resistance range: {res_range[1]:.2f} ohms')

Jaguar resistance range: 8.00 ohms
Panther resistance range: 10.90 ohms


In [26]:
res_Q1 = np.nanpercentile(resistance, 25, axis=1)
res_Q1

array([9.4  , 9.125])

In [27]:
res_Q2 = np.nanpercentile(resistance, 50, axis=1)
res_Q2

array([9.8 , 9.55])

In [28]:
res_Q3 = np.nanpercentile(resistance, 75, axis=1)
res_Q3

array([10.45 , 10.625])

In [29]:
print(f'Jaguar IQR: {res_Q3[0] - res_Q1[0]:.2f} ohms')
print(f'Panther IQR: {res_Q3[1] - res_Q1[1]:.2f} ohms')

Jaguar IQR: 1.05 ohms
Panther IQR: 1.50 ohms


In [30]:
res_var = np.nanvar(resistance,ddof=1,axis=1)
res_var

array([ 4.86      , 11.08277778])

In [31]:
print(f'Jaguar Variance = {res_var[0]:.2f} ohms')
print(f'Panther Variance = {res_var[1]:.2f} ohms')

Jaguar Variance = 4.86 ohms
Panther Variance = 11.08 ohms


In [32]:
res_std = np.nanstd(resistance,ddof=1,axis=1)
res_std

array([2.20454077, 3.32908062])

In [33]:
print(f'Jaguar Std. Variation {res_std[0]:.2f} ohms')
print(f'Panther Std. Variation {res_std[1]:.2f} ohms')

Jaguar Std. Variation 2.20 ohms
Panther Std. Variation 3.33 ohms
