# Numpy <hr style="border:3.5px solid rgba(41, 225, 106, 0.76)"></hr>

<b>Cyrus James F. Lozada</b>
<br>Computer Engineering 2-A

In [12]:
import numpy as np

In [13]:
may_array = [1, 2, 3]

In [14]:
type(may_array)

list

In [15]:
may_array = np.array([1, 2, 3])

In [16]:
np.shape(may_array)

(3,)

# 2d Array

In [17]:
import numpy as np  


In [18]:
may_array = np.array([[1, 2, 3], 
                      [4, 5, 6]])
may_array

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.shape(may_array)

(2, 3)

In [20]:
may_array.T

array([[1, 4],
       [2, 5],
       [3, 6]])

# Measure of Central Tendency

In [21]:

resistance = np.array([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 3, 10.4, 9.8],
    [10.1, 11, 9.1, 9.2, 10.8, 20, 9.9, 9.2, 9.1, 9.1,np.nan]
    ])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. ,  3. , 10.4,  9.8],
       [10.1, 11. ,  9.1,  9.2, 10.8, 20. ,  9.9,  9.2,  9.1,  9.1,  nan]])

In [22]:
np.nanmean(resistance, axis=1)

array([ 9.4 , 10.75])